---
title: "Regression Models Class Project (JHU via Coursera) - July 2014"
author: "Leif Ulstrup"
date: "July 22, 2014"
output: html_document
---

##Executive Summary



##Introduction

Our project assignment for this class (Regression Models at Johns Hopkins U via Coursera - July 2014) is to assume we work for Motor Trend Magazine and are asked to use data from a 1974 Motor Trend magazine survey of car performance for 32 automobiles to answer two questions.  The information about this data source "mtcars" can be found here:  http://stat.ethz.ch/R-manual/R-devel/library/datasets/html/mtcars.html

####The questions are:
(1) Is an automatic or manual transmission better for MPG (miles per gallon)?
(2) Quantify the MPG difference between automatic and manual transmissions?

The challenge in answering these questions is that the data do NOT include automatic AND manual transmission versions of the same cars for comparison.  Solely using the data in the mtcars data set to answer this question by trying to normalize the physical characteristics such as weight, horsepower, acceleration, cylinders, etc and then testing for differences in MPG for automatic vs. manual transmissions will likely have a low confidence factor.

Given the performance factors that are in the input data set "mtcars" are ultimately governed by physics (Newton's Laws), car designer engineering tradeoffs, and how the car was driven in testing, one can refer to the physics that drive the major factors in MPG performance to think through ways to normalize the physical characteristics in answering the question.  Per this reference:

These primary physics factors are:

(1) engine efficiency in converting the energy in a gallon of gasoline into power,
(2) mechanical losses to heat due to inefficiencies in the power transmission to the tires,
(3) rolling friction losses (these are function of the weight of the car and coefficient of rolling friction of the tires), and, most importantly at high speeds (>50mph),
(4) drag on the car where the power (energy/unit time) required to overcome 

drag = (1/2)*(fluid density of air)*(front surface "drag area" of the car)*(drag coefficient of the car body)* velocity^3

If one assumes that the test driving for the mtcars data approximated the same velocities, then the major difference in energy consumption is based on the front surface of the car * the car's drag coefficient.

The drag area and drag coefficients can vary by multiples and create major differences in fuel economy per this reference and these tables:  http://en.wikipedia.org/wiki/Automobile_drag_coefficient.

The exploratory data analysis below explores the relationship between MPG and transmission type by first exploring the relationships between MPG and Weight, MPG and Horsepower (HP), Quarter Mile time vs HP, and Quarter Mile time vs Power Ratio (Weight/HP).  In each case the data are plotted noted whether the car has an automatic (am=0) or manual transmission (am=1).  The analysis shows a number of differences between the automatic and manual car performance but also a number of overlaps in physical parameters where the data show little variaion between the two types of transmissions.  

The most striking diagram "MPG vs HP" seems to show that manual transmission cars are on a trend line of ~4 MPG superior performance when horsepower is the assumed factor affecting MPG; however, the data is limited and high horsepower manual transmission cars are relatively low weight cars (sports cars) vs. the automatic transmission set.

The 13 of 32 manual transmission cars average 24.39 mpg (with a standard deviation of 6.17) vs the automatics which are 19 of 32 cars and average 17.15 mpg (with a standard deviation of 3.834); however, it is also easy to see on the MPG vs Weight chart that the majority of the manual transmission cars are the much lighter cars.  11 of the 13 manual transmission cars are below 3000 lbs while only 1 of the 19 automatic cars is below 3000 lbs.  The MPG vs Weight trend lines would lead one to the conclusion that manual transmissions have much worse mpg than automatic for cars above 3000 lbs but again there are only 2 of 13 data points in that region.  The 95% (t-test) intervals for automatic is 8.7 mpg to 25.59 mpg and manual is 10.82 mpg to 38.0 mpg.  The mean weight of the manual transmission cars is 64% of the automatic cars.


##Exploratory Data Analysis


```{r eda, echo=TRUE}

require(car) # this package includes the function scatterplot() which is useful for the visuals below

require(graphics)

data(mtcars) # confirm this is refreshed

# do a quick check of the relationships using the pairs() function to display
pairs(mtcars, main = "mtcars data")

# do basic analysis on the data set
autoMeanMPG <- mean(mtcars[mtcars$am == 0,]$mpg)  # am=0 automatic transmission
autosdMPG <- sd(mtcars[mtcars$am == 0,]$mpg)  # am=0 automatic transmission
nauto <- nrow(mtcars[mtcars$am == 0,])
automaticRange <- autoMeanMPG+c(-1,1)*qt(.975, df=nauto-2)*autosdMPG # 95% confidence range
wtMeanauto <- mean(mtcars[mtcars$am == 0,]$wt)

manualMeanMPG <- mean(mtcars[mtcars$am == 1,]$mpg)  # am=1 automatic transmission
manualsdMPG <- sd(mtcars[mtcars$am == 1,]$mpg)   # am=1 automatic transmission
nmanual <- nrow(mtcars[mtcars$am == 1,])
manualRange <- manualMeanMPG+c(-1,1)*qt(.975, df=nmanual-2)*manualsdMPG # 95% confidence range
wtMeanmanual <- mean(mtcars[mtcars$am == 1,]$wt)

manualWTtoautoWTratio <- wtMeanmanual/wtMeanauto

# dive in and start looking at relationships visually
scatterplot(mpg ~ wt | am, data=mtcars, xlab="Weight (lb/1000)", ylab="Miles Per Gallon", main="MPG vs Weight\n 1974 Motor Trend US magazine\n (0: automatic transmission, 1: manual transmission)", labels=row.names(mtcars), legend.coords="topright", smoother=FALSE)

scatterplot(mpg ~ hp | am, data=mtcars, xlab="Horsepower", ylab="Miles Per Gallon", main="MPG vs HP\n 1974 Motor Trend US magazine\n (0: automatic transmission, 1: manual transmission)", labels=row.names(mtcars), legend.coords="topright", smoother=FALSE)

scatterplot(hp ~ wt | am, data=mtcars, xlab="Weight (lb/1000)", ylab="Horsepower", main="HP vs Weight\n 1974 Motor Trend US magazine\n (0: automatic transmission, 1: manual transmission)", labels=row.names(mtcars), legend.coords="topright", smoother=FALSE)

scatterplot(qsec ~ hp | am, data=mtcars, xlab="Horsepower", ylab="Seconds to Quarter Mile", main="Quarter Mile Time vs HP\n 1974 Motor Trend US magazine\n (0: automatic transmission, 1: manual transmission)", labels=row.names(mtcars), legend.coords="topright", smoother=FALSE)

mtcars$powerRatio <- mtcars$wt*1000/mtcars$hp

scatterplot(qsec ~ powerRatio | am, data=mtcars, xlab="Weight (lbs)/Horsepower", ylab="Seconds to Quarter Mile", main="Quarter Mile Time vs Power Ratio\n 1974 Motor Trend US magazine\n (0: automatic transmission, 1: manual transmission)", labels=row.names(mtcars), legend.coords="topright", smoother=TRUE)


#
# Using external sources for reference to compare to a larger body of car performance data
# using data from "Calculators for 1/4-Mile ET & MPH vs. HP and Weight" http://www.stealth316.com/2-calc-hp-et-mph.htm

mtcars$MPHestimate <- 215.39*(mtcars$hp/(mtcars$wt*1000))^(0.3018)
mtcars$QuarterMileTimeEstimate <- 7.3571*((mtcars$wt*1000)/mtcars$hp)^(0.2574)
mtcars$HPestimate <- (mtcars$wt*1000)/(mtcars$qsec/7.3571)^3.885
mtcars$HPestimateToActualHPRatio <- mtcars$HPestimate/mtcars$hp


# test weight (wt) as the best predictor of MPG
summary(model1auto <- lm(mpg ~ wt, data=mtcars[mtcars$am==0,])) # test manual relationship to weight
confint(model1auto)
summary(model1manual <- lm(mpg ~ wt, data=mtcars[mtcars$am==1,])) # test automatic relationship to weight
confint(model1manual)
summary(model1 <- lm(mpg ~ wt, data=mtcars))
confint(model1)
#plot(mtcars$wt, model1$residuals)
#abline(h=0)
par(mfrow=c(2,2))
plot(model1)

#test horsepower(hp) as the best predictor of MPG
summary(model2auto <- lm(mpg ~ hp, data=mtcars[mtcars$am==0,])) # test manual relationship to hp
confint(model2auto)
summary(model2manual <- lm(mpg ~ hp, data=mtcars[mtcars$am==1,])) # test automatic relationship to hp
confint(model2manual)
summary(model2 <- lm(mpg ~ hp, data=mtcars))
confint(model2)
#plot(mtcars$hp, model2$residuals)
#abline(h=0)
par(mfrow=c(2,2))
plot(model2)

# source "R in Action" by Robert Kabacoff, page 186-188
# recommends that one explore the interrelationship between wt and hp together as a factor
# so...
fithpANDwt <- lm(mpg ~ hp + wt + hp:wt, data = mtcars)
summary(fithpANDwt)
plot(effect("hp:wt", fithpANDwt,list(wt=c(2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0))), multiline=TRUE)

```

##Conclusions




####For Fun - Analysis of This Question Using Modern Car Capabilities

This question about whether manual or automatic transmissions provide superior MPG and other advantages continues to this day.  Most car analysts suggest that very sophisticated modern day automatic transmissions (especially "continuous variable") are as good are even better than manual transmissions for fuel economy.  There is a funny version of this discussion with the famous "Frick and Frack Brothers Car Talk Series on NPR" dated 8/21/12 and located here: http://www.cartalk.com/content/today-manual-transmission-myths-debunked .  Here is another source that shows that it is a toss up also though the title indicates otherwise:  http://www.consumerreports.org/cro/2012/01/save-gas-and-money-with-a-manual-transmission/index.htm

Here is another reference exploring statistical analysis of a broad range of automobile performance chracteristics starting with regressiona analysis from the 1950's to today.  The analysis does not explore the automatic vs. manual discussion but does look at the ratios between quarter mile time, quarter mile MPH, weight, horsepower, Power Ratio, etc.  It can be found here:  "Calculators for 1/4-Mile ET & MPH vs. HP and Weight" http://www.stealth316.com/2-calc-hp-et-mph.htm